// components/Layout.js
import { Box } from "@mui/material";
import Head from "next/head";
import Sidebar from "./Siderbar"; // Import your Sidebar component

const Layout = ({ children }: any) => {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div>
                <Sidebar />
                <Box ml={12} mr={5}>
                    <main>{children}</main>
                </Box>
            </div>
        </>
    );
};

export default Layout;
